[package]
name = "paytr"
version = "0.1.0"
edition = "2021"
author = ["Oguzhan Dogan"]
description = ["Paytr Package for Rust"]



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
